import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { ThemeToggle } from "@/components/features/theme/toggle";
import { Link } from "@/components/ui/link/link";

const nunitoFont = localFont({
	src: "./nunito.ttf",
});

export const metadata: Metadata = {
	title: "Smoothed",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className={nunitoFont.className}>
			<body
				className="bg text-1 overflow-y-auto selection:surface-primary-solid pt-12"
				style={{ minHeight: "100svh" }}
			>
				<ThemeProvider
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
					attribute={"class"}
				>
					<header className="px-16d h-12 flex items-center bg-2 fixed top-0 z-10 shadow-lifted-4 w-screen">
						<div className="max-w-414 flex-grow flex items-center justify-between mx-auto">
							<Link href={"/"}>
								{/** biome-ignore lint/performance/noImgElement: 'svg' */}
								<img
									src={"/favicon.svg"}
									alt="logo"
									style={{ width: 32, height: 32 }}
								/>
							</Link>
							<div className="flex gap-16d items-center max-w-200 flex-grow px-18d">
								<Link href="/get-started">Get Started</Link>
								<Link href="/theme-editor">Theme Editor</Link>
								<Link href="/components">Components</Link>
							</div>
							<ThemeToggle />
						</div>
					</header>
					<main
						style={{ minHeight: "calc(100dvh - 3rem)" }}
						className="flex flex-col w-screen px-4"
					>
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
