import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { ThemeToggle } from "@/components/features/theme/toggle";

import { Link } from "@/components/ui/navigation/link/link";

const sansFont = localFont({
	src: "./nunito.ttf",
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Smoothed",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			style={{ scrollbarGutter: "stable" }}
		>
			<body
				className={`${sansFont.variable} ${sansFont.className} text-16 overflow-y-auto pt-12 selection sfc-default`}
				style={{ minHeight: "100svh" }}
			>
				<ThemeProvider
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
					attribute={"class"}
				>
					<div className="h-12 flex items-center justify-between fixed top-0 z-10 zero-elevation-5 w-screen [--sun-x:0]">
						<div className="h-full sfc-shadow flex-1 rel-elevation-10 sfc-default"></div>
						<div className="h-full grow max-w-200 basis-200 sfc-shadow flex-1 shrink-0 rel-elevation-5 sfc-default"></div>
						<div className="h-full sfc-shadow flex-1 rel-elevation-10 sfc-default"></div>
					</div>
					<header className="px-4 h-12 flex items-center fixed top-0 z-10 sfc-default rel-elevation-5 zero-elevation-5 w-screen">
						<div className="max-w-414 grow flex items-center justify-between mx-auto">
							<Link href={"/"}>
								{/** biome-ignore lint/performance/noImgElement: 'svg' */}
								<img
									src={"/favicon.svg"}
									alt="logo"
									style={{ width: 32, height: 32 }}
								/>
							</Link>
							<div className="flex gap-16d items-center max-w-200 flex-grow px-18d">
								<Link href="/get-started">Get Started</Link>
								<Link href="/theme-editor">Theme Editor</Link>
								<Link href="/components">Components</Link>
							</div>
							<ThemeToggle />
						</div>
					</header>
					<main
						style={{ minHeight: "calc(100dvh - 3rem)" }}
						className="flex flex-col w-screen px-8"
					>
						{children}
					</main>
					<div className="px-8">
						<footer className="relative m-auto max-w-200 sfc-shadow px-4 h-12 flex items-center surface-1 sfc-default rel-elevation-10 zero-elevation-10">
							footer
						</footer>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
