import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Link from "next/link";
import { ThemeToggle } from "@/components/features/theme/toggle";

const nunitoFont = localFont({
	src: "./nunito.ttf",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className={nunitoFont.className}>
			<body
				className="bg-neutral text-neutral overflow-x-hidden"
				style={{ minHeight: "100svh" }}
			>
				<ThemeProvider
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
					attribute={"class"}
				>
					<header className="px-16d py-12d bg-neutral-2 flex items-center justify-between sticky top-0 z-1 shadow-4d">
							<Link href={"/"}>
								{/** biome-ignore lint/performance/noImgElement: 'svg' */}
								<img
									src={"/favicon.svg"}
									alt="logo"
									style={{ width: 32, height: 32 }}
								/>
							</Link>
						<div className="flex gap-16d items-center max-w-200 flex-grow px-4">

							<Link href="/get-started" className="text-primary underline">
								Get Started
							</Link>
							<Link href="/theme-editor" className="underline text-primary">
								Theme Editor
							</Link>
							<Link href="/components" className="underline text-primary">
								Components
							</Link>
						</div>
						<ThemeToggle />
					</header>
					<main className="overflow-y-auto" style={{height: "calc(100dvh - 3rem)"}}>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
